#' Explore and filter genomic data
#'
#' @description
#' \strong{`explore_genomes`} provides an interactive, opinionated workflow for
#' exploring genomic quality metrics and applying an initial sequence of
#' filters. It is intended as a starting point, especially for users who are
#' learning about their dataset and selecting filtering thresholds.
#'
#' The workflow is not a universal filtering recipe. The appropriate filters,
#' thresholds, and order depend on the organism, sequencing design, marker
#' type, and study objectives. Experienced users should generally build a
#' dataset-specific workflow from the individual `filter_*()` and `detect_*()`
#' functions in `radr`.
#'
#' @param data A GDS filepath or an open `SeqVarGDSClass` object. Other genomic
#'   formats must first be imported with an appropriate `genometranslator`
#'   reader, such as [genometranslator::read_vcf()],
#'   [genometranslator::read_dart()], or [genometranslator::read_plink()].
#' @param interactive.filter Logical. If `TRUE`, figures and questions guide
#'   the selection of filtering thresholds. If `FALSE`, thresholds are supplied
#'   through `...`. Default: \code{interactive.filter = TRUE}.
#' @param output Optional output format passed to
#'   [genometranslator::genome_translator()]. If `NULL`, no additional genomic
#'   format is generated. Default: \code{output = NULL}.
#' @param filename Optional prefix used for generated output files.
#'   Default: \code{filename = NULL}.
#' @param verbose Logical. Display progress messages.
#'   Default: \code{verbose = TRUE}.
#' @param parallel.core Number of processor cores available to compatible
#'   operations.
#'   Default: \code{parallel.core = parallel::detectCores() - 1}.
#' @param ... Filtering thresholds and advanced options passed to the individual
#'   `radr` filtering and detection functions.
#'
#' @details
#' The standard workflow considers DArT reproducibility when available,
#' monomorphic and common markers, individual quality, allele frequency,
#' coverage, genotyping rate, SNP position and number, linkage disequilibrium,
#' mixed and duplicate genomes, and Hardy-Weinberg equilibrium. Steps can be
#' enabled, disabled, or configured through `...`.
#'
#' The function creates a dated workflow folder containing the parameter log,
#' diagnostic figures, blacklists and whitelists, final metadata, and summary
#' statistics. Statistics are generated for these files and are not retained as
#' a separate object in the returned value.
#'
#' @section Interactive and tailored workflows:
#' Interactive mode is designed to help users inspect diagnostic plots and
#' understand the consequences of candidate thresholds. For reproducible batch
#' analyses, use `interactive.filter = FALSE` and provide explicit thresholds.
#' For mature analyses, call the relevant functions individually so their order
#' and configuration reflect the dataset.
#'
#' @return A named list containing:
#' \describe{
#'   \item{gds}{The filtered GDS object.}
#'   \item{output}{The object generated by
#'   [genometranslator::genome_translator()], or `"not selected"` when no
#'   output format was requested.}
#' }
#'
#' @examples
#' \dontrun{
#' # Import a VCF with genometranslator, then explore it with radr
#' gds <- genometranslator::read_vcf(
#'   data = "shark.vcf",
#'   strata = "shark_strata.tsv"
#' )
#'
#' shark <- radr::explore_genomes(data = gds)
#'
#' # Experienced users can construct a tailored workflow instead
#' filtered <- gds |>
#'   radr::filter_genotyping(
#'     interactive.filter = FALSE,
#'     filter.genotyping = 0.20
#'   ) |>
#'   radr::filter_ma(
#'     interactive.filter = FALSE,
#'     filter.ma = 2
#'   )
#' }
#'
#' @seealso
#' [filter_individuals()], [filter_ma()], [filter_coverage()],
#' [filter_genotyping()], [filter_ld()], [detect_mixed_genomes()],
#' [detect_duplicate_genomes()], and
#' [genometranslator::genome_translator()].
#'
#' @export
#' @author Thierry Gosselin \email{thierrygosselin@@icloud.com}
explore_genomes <- function(
  data,
  interactive.filter = TRUE,
  output = NULL,
  filename = NULL,
  verbose = TRUE,
  parallel.core = parallel::detectCores() - 1,
  ...
) {

  # Common startup -------------------------------------------------------------
  .start <- tgbase::startup(
    package = "radr",
    f.name = "explore_genomes",
    verbose = verbose
  )
  file.date <- .start$file.date
  on.exit(tgbase::teardown(.start), add = TRUE)
  res <- list()

  # Function call and dotslist -------------------------------------------------
  rad.dots <- radr_dots(
    func.name = as.list(sys.call())[[1]],
    fd = rlang::fn_fmls_names(),
    args.list = as.list(environment()),
    dotslist = rlang::dots_list(..., .homonyms = "error", .check_assign = TRUE),
    keepers = c(
      "subsample.markers.stats",
      "filter.reproducibility", "filter.individuals.missing",
      "filter.individuals.heterozygosity", "filter.individuals.coverage.total",
      "filter.individuals.coverage.median", "filter.individuals.coverage.iqr",
      "filter.common.markers", "filter.monomorphic", "filter.ma",
      "filter.coverage", "filter.genotyping", "filter.snp.position.read",
      "filter.snp.number", "filter.short.ld", "filter.long.ld", "long.ld.missing",
      "ld.method", "detect.mixed.genomes", "ind.heterozygosity.threshold",
      "detect.duplicate.genomes", "dup.threshold",
      "filter.hwe", "hw.pop.threshold", "midp.threshold",
      "random.seed", "path.folder", "filename",
      "whitelist.markers",
      "internal"),
    deprecated = c("pop.select, pop.labels", "blacklist.id"),
    verbose = FALSE
  )
  filter.common.markers.bk <- filter.common.markers
  filter.monomorphic.bk <- filter.monomorphic
  filter.individuals.missing.bk <- filter.individuals.missing
  filter.individuals.heterozygosity.bk <- filter.individuals.heterozygosity
  filter.individuals.coverage.total.bk <- filter.individuals.coverage.total
  filter.individuals.coverage.median.bk <- filter.individuals.coverage.median
  filter.individuals.coverage.iqr.bk <- filter.individuals.coverage.iqr
  filter.ma.bk <- filter.ma
  filter.coverage.bk <- filter.coverage
  filter.genotyping.bk <- filter.genotyping
  filter.snp.position.read.bk <- filter.snp.position.read
  filter.snp.number.bk <- filter.snp.number
  filter.short.ld.bk <- filter.short.ld
  filter.long.ld.bk <- filter.long.ld
  long.ld.missing.bk <- long.ld.missing
  ld.method.bk <- ld.method
  detect.mixed.genomes.bk <- detect.mixed.genomes
  ind.heterozygosity.threshold.bk <- ind.heterozygosity.threshold
  detect.duplicate.genomes.bk <- detect.duplicate.genomes
  dup.threshold.bk <- dup.threshold
  filter.hwe.bk <- filter.hwe
  hw.pop.threshold.bk <- hw.pop.threshold
  midp.threshold.bk <- midp.threshold


  # Test
  # internal <- FALSE
  # path.folder <- NULL
  # random.seed <- NULL


  # Checking for missing and/or default arguments ------------------------------
  if (missing(data)) rlang::abort("data is missing")

  data.type <- tryCatch(
    genometranslator::detect_genomic_format(data),
    error = function(cnd) "unsupported"
  )
  if (!data.type %in% c("SeqVarGDSClass", "gds.file")) {
    rlang::abort(
      c(
        "`explore_genomes()` requires a GDS file or object.",
        i = paste0(
          "The supplied input was detected as `", data.type, "`."
        ),
        i = paste0(
          "Import it first with an appropriate `genometranslator` ",
          "reader, then pass the resulting GDS to `explore_genomes()`."
        )
      )
    )
  }

  # Required packages ----------------------------------------------------------
  if (interactive.filter) {
    tgbase::check_package(package = "HardyWeinberg")
    tgbase::check_package(package = "SeqArray", cran = FALSE, bioc = TRUE)
    tgbase::check_package(package = "SNPRelate", cran = FALSE, bioc = TRUE)
  }

  # Folders---------------------------------------------------------------------
  # wf for working folder
  # radr.folder : the 01_radr folder to put most things...
  wf <- path.folder <- generate_folder(
    rad.folder = "explore_genomes",
    path.folder = path.folder,
    prefix.int = TRUE,
    append.date = TRUE,
    internal = internal,
    file.date = file.date,
    verbose = verbose)

  radr.folder <- generate_folder(
    rad.folder = "radr",
    path.folder = path.folder,
    prefix.int = TRUE,
    internal = FALSE,
    file.date = file.date,
    verbose = verbose)

  # write the dots file
  tgbase::write_tgbase_tsv(
    data = rad.dots,
    path.folder = radr.folder,
    filename = "radr_explore_genomes_args",
    date = TRUE,
    internal = internal,
    write.message = "Function call and arguments stored in: ",
    verbose = verbose
  )

  # Random seed ----------------------------------------------------------------
  if (is.null(random.seed)) {
    random.seed <- sample(x = 1:1000000, size = 1)
    set.seed(random.seed)
  } else {
    set.seed(random.seed)
  }
  readr::write_lines(x = random.seed, file = file.path(radr.folder, "random.seed"))
  if (verbose) message("File written: random.seed (", random.seed,")")

  # Filter parameter file: generate --------------------------------------------
  filters.parameters <- filter_parameters(
    generate = TRUE,
    initiate = FALSE,
    update = FALSE,
    parameter.obj = NULL,
    path.folder = radr.folder,
    file.date = file.date,
    verbose = verbose)

  # GDS input ------------------------------------------------------------------
  if (data.type == "gds.file") {
    gds <- genometranslator::read_genome(data = data, verbose = verbose)
  } else {
    gds <- data
  }

  source <- genometranslator::extract_data_source(gds) # to know if dart data or not...

  # Filter reproducibility -----------------------------------------------------
  if ("dart" %in% source) {
    # Filter parameter file: initiate
    filters.parameters <- filter_parameters(
      generate = FALSE,
      initiate = TRUE,
      update = FALSE,
      parameter.obj = filters.parameters,
      data = gds,
      path.folder = radr.folder,
      file.date = file.date,
      verbose = verbose)

    gds <- filter_dart_reproducibility(
      data = gds,
      interactive.filter = interactive.filter,
      filter.reproducibility = filter.reproducibility,
      parallel.core = parallel.core,
      verbose = verbose,
      parameters = filters.parameters,
      path.folder = wf,
      internal = FALSE)
  }

  # Filter_monomorphic----------------------------------------------------------
  gds <- filter_monomorphic(
    data = gds,
    filter.monomorphic = filter.monomorphic.bk,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)

  # Filter common markers ------------------------------------------------------
  gds <- filter_common_markers(
    data = gds,
    filter.common.markers = filter.common.markers.bk,
    fig = TRUE,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)

  # Filter Whitelist------------------------------------------------------------
  gds <- filter_whitelist(
    data = gds,
    whitelist.markers = whitelist.markers,
    verbose = verbose,
    path.folder = wf,
    parameters = filters.parameters,
    biallelic = biallelic,
    internal = FALSE)

  # Genotypes metadata ---------------------------------------------------------
  # check for coverage information...
  # genotypes.meta <- extract_genotypes_metadata(gds, index.only = TRUE)
  # count.data <- "ALLELE_REF_DEPTH" %in% genotypes.meta
  # coverage.info <- "READ_DEPTH" %in% genotypes.meta
  # genotypes.meta <- NULL

  # Filter_individuals----------------------------------------------------------
  gds <- filter_individuals(
    data = gds,
    interactive.filter = interactive.filter,
    filter.individuals.missing = filter.individuals.missing.bk,
    filter.individuals.heterozygosity = filter.individuals.heterozygosity.bk,
    filter.individuals.coverage.total = filter.individuals.coverage.total.bk,
    filter.individuals.coverage.median = filter.individuals.coverage.median.bk,
    filter.individuals.coverage.iqr = filter.individuals.coverage.iqr.bk,
    parallel.core = parallel.core,
    verbose = verbose,
    path.folder = wf,
    parameters = filters.parameters,
    internal = FALSE
  )

  # Filter MAC------------------------------------------------------------------
  gds <- filter_ma(
    data = gds,
    interactive.filter = interactive.filter,
    filter.ma = filter.ma.bk,
    filename = NULL,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)


  # Filter coverage-------------------------------------------------------------
  gds <- filter_coverage(
    data = gds,
    interactive.filter = interactive.filter,
    filter.coverage = filter.coverage.bk,
    filename = NULL,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)

  # Filter genotyping---------------------------------------------------------
  gds <- filter_genotyping(
    data = gds,
    interactive.filter = interactive.filter,
    filter.genotyping = filter.genotyping.bk,
    filename = NULL,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)

  # Filter SNP position on the read---------------------------------------------
  gds <- filter_snp_position_read(
    data = gds,
    interactive.filter = interactive.filter,
    filter.snp.position.read = filter.snp.position.read.bk,
    filename = NULL,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)


  # Filter snp number per locus ------------------------------------------------
  gds <- filter_snp_number(
    data = gds,
    interactive.filter = interactive.filter,
    filter.snp.number = filter.snp.number.bk,
    filename = NULL,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    path.folder = wf,
    internal = FALSE)

  # Filter Linkage disequilibrium --------------------------------------------
  continue.with.ld <- "y"

  if (interactive.filter) {
    continue.with.ld <- tgbase::question(
      x = "\n\nDo you want to filter the dataset using short distance ld  ? (y/n):",
      answer.opt = c("y", "n"))
  }

  if (continue.with.ld == "y") {
    gds <- filter_ld(
      data = gds,
      interactive.filter = interactive.filter,
      filter.short.ld = filter.short.ld.bk,
      filter.long.ld = filter.long.ld.bk,
      parallel.core = parallel.core,
      filename = NULL,
      verbose = verbose,
      long.ld.missing = long.ld.missing.bk,
      ld.method = ld.method.bk,
      parameters = filters.parameters,
      path.folder = wf,
      internal = FALSE)
  }

  # Detect mixed genomes -------------------------------------------------------
  gds <- detect_mixed_genomes(
    data = gds,
    interactive.filter = interactive.filter,
    detect.mixed.genomes = detect.mixed.genomes.bk,
    ind.heterozygosity.threshold = ind.heterozygosity.threshold.bk,
    parameters = filters.parameters,
    verbose = verbose,
    parallel.core = parallel.core,
    path.folder = wf,
    internal = FALSE)

  #Detect duplicate genomes ---------------------------------------------------
  gds <- detect_duplicate_genomes(
    data = gds,
    interactive.filter = interactive.filter,
    detect.duplicate.genomes = detect.duplicate.genomes.bk,
    dup.threshold = dup.threshold.bk,
    parallel.core = parallel.core,
    verbose = verbose,
    parameters = filters.parameters,
    random.seed = random.seed,
    path.folder = wf,
    internal = FALSE)

  # Filter HWE -----------------------------------------------------------------
  gds <- filter_hwe(
    data = gds,
    interactive.filter = interactive.filter,
    filter.hwe = filter.hwe.bk,
    strata = NULL,
    hw.pop.threshold = hw.pop.threshold.bk,
    midp.threshold = midp.threshold.bk,
    parallel.core = parallel.core,
    parameters = filters.parameters,
    path.folder = wf,
    verbose = verbose,
    internal = FALSE)


  # Final Sync GDS -----------------------------------------------------------
  if (verbose) message("\nPreparing output files...")
  markers.meta <- genometranslator::extract_markers_metadata(
    gds = gds,
    whitelist = TRUE)

  strata <- genometranslator::extract_individuals_metadata(
    gds = gds,
    # ind.field.select = c("INDIVIDUALS", "STRATA"),
    whitelist = TRUE)

  genometranslator::sync_gds(
    gds = gds,
    samples = strata$INDIVIDUALS,
    variant.id = markers.meta$VARIANT_ID
  )

  # FINAL PREP
  # filtered data folder
  path.folder <- generate_folder(
    rad.folder = "filtered",
    path.folder = wf,
    internal = FALSE,
    file.date = file.date,
    verbose = verbose)

  # Whitelist
  tgbase::write_tgbase_tsv(
    data = markers.meta,
    path.folder = path.folder,
    filename = "whitelist.markers",
    date = TRUE,
    internal = FALSE,
    write.message = "standard",
    verbose = verbose
  )

  # blacklist
  bl <- genometranslator::extract_markers_metadata(gds = gds, blacklist = TRUE)
  if (nrow(bl) > 0) {
    tgbase::write_tgbase_tsv(
      data = bl,
      path.folder = path.folder,
      filename = "blacklist.markers",
      date = TRUE,
      internal = FALSE,
      write.message = "standard",
      verbose = verbose
    )
  }


  # writing the blacklist of id
  blacklist.id <- genometranslator::extract_individuals_metadata(gds = gds, blacklist = TRUE)
  if (nrow(blacklist.id) > 0) {
    tgbase::write_tgbase_tsv(
      data = blacklist.id,
      path.folder = path.folder,
      filename = "blacklist.id",
      date = TRUE,
      internal = FALSE,
      write.message = "standard",
      verbose = verbose
    )
  }

  # Generate new strata
  tgbase::write_tgbase_tsv(
    data = strata,
    path.folder = path.folder,
    filename = "strata.filtered",
    date = TRUE,
    internal = FALSE,
    write.message = "Writing the filtered strata: ",
    verbose = verbose
  )

  # Statistics after filtering -------------------------------------------------
  if (verbose) message("\nGenerating statistics after filtering")

  # Individuals and markers stats
  invisible(genometranslator::generate_stats(
    gds = gds,
    individuals = TRUE,
    markers = TRUE,
    missing = TRUE,
    heterozygosity = TRUE,
    coverage = TRUE,
    allele.coverage = TRUE,
    mac = TRUE,
    snp.position.read = TRUE,
    snp.per.locus = TRUE,
    path.folder = path.folder,
    file.date = file.date,
    parallel.core = parallel.core,
    verbose = verbose
  ))

  # Optional output translation -----------------------------------------------
  if (is.null(output)) {
    res$output <- "not selected"
  } else {
    output.filename <- filename
    if (is.null(output.filename)) output.filename <- "filtered_genome"
    output.filename <- file.path(path.folder, basename(output.filename))

    if (verbose) {
      message(
        "\nWriting requested genomic output: ",
        paste(output, collapse = ", ")
      )
    }
    res$output <- genometranslator::genome_translator(
      data = gds,
      strata = strata,
      output = output,
      parallel.core = parallel.core,
      filename = output.filename,
      verbose = verbose
    )
    if (is.null(res$output)) res$output <- "written"
  }
  genometranslator::summary_gds(gds = gds, verbose = TRUE)
  res$gds <- gds
  return(res)
} # End explore_genomes
